wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part001.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part002.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part003.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part004.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part005.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part006.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part007.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part008.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part009.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part010.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part011.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part012.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part013.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part014.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part015.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part016.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part017.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part018.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part019.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part020.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part021.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part022.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part023.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part024.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part025.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part026.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part027.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part028.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part029.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part030.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part031.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part032.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part033.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part034.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part035.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part036.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part037.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part038.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part039.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part040.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part041.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part042.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part043.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part044.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part045.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part046.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part047.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part048.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part049.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part050.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part051.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part052.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part053.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part054.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part055.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part056.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part057.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part058.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part059.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part060.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part061.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part062.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part063.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part064.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part065.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part066.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part067.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part068.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part069.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part070.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part071.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part072.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part073.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part074.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part075.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part076.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part077.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part078.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part079.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part080.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part081.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part082.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part083.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part084.rar
wget https://raw.githubusercontent.com/Benjamin8330/ubi-goggles/refs/heads/main/git_src/opensource_antivirus.part085.rar

